###

# 채팅 메시지 보내기
POST http://localhost:8080/api/chat
Content-Type: application/json

{
  "customerKey": "customer123",
  "carModel": "더 뉴 아이오닉 5",
  "dealerShop": "서울 강남 대리점",
  "chatMessge": "저렴한 전기차를 찾고 있습니다."
}


###

