spring:
  application:
    name: springAi
  ai:
    openai:
      api-key: Your_apiKey
      model: gpt-4o                        # 모델 이름 명시
      max-tokens: 2000                     # 출력 토큰 제한 설정 (필요에 따라 가변)
      temperature: 0.8                     # Chatbot의 응답의 창의성 설정
aws:
  dynamodb:
    region: ap-northeast-2 # 사용할 AWS Region (예: 서울 리전)
    access-key: Your_accessKey # AWS 액세스 키
    secret-key: Your_secretKey  # AWS 비밀 키

server:
  servlet:
    session:
      timeout: 30m # 세션 타임아웃 설정 (30분)